DROP TABLE users CASCADE CONSTRAINT;

DROP TABLE movie CASCADE CONSTRAINT;

DROP TABLE reasons CASCADE CONSTRAINT;

CREATE TABLE reasons (
email VARCHAR(20) PRIMARY KEY, 
reason varchar(20) NOT NULL
);

CREATE TABLE users (
	email VARCHAR2(20) PRIMARY KEY,
	pw VARCHAR2(50) NOT NULL,
	name VARCHAR2(20) NOT NULL,
	age NUMBER(19,
4) NOT NULL,
	card NUMBER(19,
4) NOT NULL,
	planType VARCHAR(20) NOT NULL,
	paymentDate VARCHAR(20) NOT NULL
);

CREATE TABLE movie (
	name VARCHAR2(200) PRIMARY KEY,
	genre VARCHAR2(50) NOT NULL,
	director VARCHAR2(100) NOT NULL,
	age NUMBER(19,
4) NOT NULL,
	planType VARCHAR2(20) NOT NULL
);

commit;